[project]
name = "fdem-scanner-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "pytest>=8.4.1",
    "simpeg>=0.24.0",
]
